# Generated by Django 5.0.1 on 2024-10-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee", name="name", field=models.CharField(max_length=255),
        ),
    ]
